# Generated by Django 2.2.7 on 2020-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='clubname',
            new_name='club_name',
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=50),
        ),
    ]
