# Generated by Django 2.2.7 on 2020-03-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20200313_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
