# Generated by Django 2.2.6 on 2020-03-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_auto_20200313_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(max_length=30),
        ),
    ]
