# Generated by Django 2.2.7 on 2020-03-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0006_auto_20200313_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterField(
            model_name='post',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
    ]
