# Generated by Django 2.2.7 on 2020-03-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0007_auto_20200313_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['updated_on']},
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(choices=[('Coding Club', 'Coding Club IITG'), ('Electronics', 'Electroncis Club IITG'), ('Robotics', 'Robotics Club IITG'), ('LitSoc', 'Literary Society IITG'), ('Xpressions', 'Drama Club IITG'), ('Aeromodelling', 'Aeromodelling Club IITG'), ('Cadence', 'Dance Club IITG'), ('IITG.AI', 'Artificial intelligence Club IITG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
    ]
